name: random

version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
description: Sample for using a native library
homepage: https://github.com/MikeMitterer/cmake-dart-extension-master

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  logging: '>=0.11.1 <0.12.0'
  logging_handlers: ">=0.8.0 <0.9.0"

  rpc: '>=0.5.0 <0.6.0'
  shelf: '>=0.6.0 <0.7.0'
  shelf_route: '>=0.13.4 <0.14.0'
  shelf_rpc: '>=0.0.3 <0.0.4'

